### ISSUE TITLE
[Need Help!] Not works on Windows Server 2025 with same configuration that works well on Server 2022

### ISSUE THREAD

**Issue by zhw618** [klzgrad/naiveproxy#685]
### Environment

the result of the following commands:
  - `naive --version` or the screenshot of About Dialog (for desktop users)
 ~~~cmd
>naive --version
naive 130.0.6723.40
~~~
### Description

Hello,

I’ve been using NaiveProxy without issues on Windows 2022. However, after the official release of Windows Server 2025, I encountered problems running NaiveProxy with the same configuration and setup on the new server. The proxy fails to work on Windows Server 2025, even though the same configuration file works fine on Windows 10/Server 2022.

I suspect the issue may be related to enhanced security measures in Windows Server 2025, such as stricter TLS settings or changes in supported cipher suites. Could you please assist in identifying what might be causing this issue? Below is the config_zhw.json file I’ve been using:
~~~json
{
  "listen": "socks://127.0.0.1:10808",
  "proxy": "quic://zhw:zhw@zhw.abc.com:8444",
  "log": ""
}
~~~
Specifically, when running the client with the command:
~~~cmd
C:\>  naive.exe  config_zhw.json
~~~

I would appreciate any guidance or suggestions.

Thank you!
---------------------------------------------------------------------
server side ,   the  log : 
~~~bash
[root@vital-kitten-3 ~]# systemctl status caddy2 -l
● caddy2.service - Caddy
   Loaded: loaded (/etc/systemd/system/caddy2.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2024-10-18 22:17:28 CST; 3 weeks 3 days ago
     Docs: https://caddyserver.com/docs/
 Main PID: 16333 (caddy2)
   CGroup: /system.slice/caddy2.service
           └─16333 /usr/bin/caddy2 run --environ --config /etc/caddy/Caddyfile2

Nov 12 00:23:36 vital-kitten-3.localdomain caddy2[16333]: {"level":"error","ts":1731342216.528477,"logger":"http.log.error","msg":"read tcp 66.112.211.111:53410->204.79.197.234:443: read: connection reset by peer","request":{"remote_ip":"125.121.139.127","remote_port":"35234","proto":"HTTP/2.0","method":"CONNECT","host":"204.79.197.234:443","uri":"204.79.197.234:443","headers":{"Padding":["*>'?<,<(<\",@)#+!XXXXXXXXXXXXX"],"Proxy-Authorization":[]},"tls":{"resumed":false,"version":772,"cipher_suite":4867,"proto":"h2","server_name":"chenj.home.kg"}},"duration":33.020187992}
Nov 12 01:03:04 vital-kitten-3.localdomain caddy2[16333]: {"level":"error","ts":1731344584.5269713,"logger":"http.log.error","msg":"read tcp 66.112.211.222:23948->108.177.104.189:443: read: connection reset by peer","request":{"remote_ip":"125.121.139.127","remote_port":"35234","proto":"HTTP/2.0","method":"CONNECT","host":"108.177.104.189:443","uri":"108.177.104.188:443","headers":{"Padding":[")\"?<@<<&+#\"*&;;#"],"Proxy-Authorization":[]},"tls":{"resumed":false,"version":772,"cipher_suite":4867,"proto":"h2","server_name":"chenj.home.kg"}},"duration":160.182277563}
......
~~~

**Comment by Chilledheart** [comment]
See https://github.com/klzgrad/naiveproxy/issues/612.

**Comment by Chilledheart** [comment]
@zhw618 you need to install it at the trusted root, pure installation doesn't work. BTW can you attach the output of "gci Cert:\LocalMachine\Root" and the output of naive command? The later can show the correct error number which is used to locate the  issue.

**Comment by Chilledheart** [comment]
Keep in mind there are two ISRG CAs. If you have imported ISRG Root X1, you properly need to import the X2 one as well.

For example, the output of my machine shows ISRG Root X2 is missing.
```
PS C:\Users\HKY> gci Cert:\LocalMachine\Root | findstr  ISRG
CABD2A79A1076A31F21D253635CB039D4329A5E8  CN=ISRG Root X1, O=Internet Security Research Group, C=US
```

And the output of [yass](https://github.com/Chilledheart/yass) also tells the same story (running under command line `yass.exe -logtostderr`)
```
[7480:1112/191406.017:INFO:asio_ssl.cpp(716)] Missing ISRG Root X2 CA
```

**Comment by Chilledheart** [comment]
> If I am not wrong, all new versions of Windows 11 (include Windows Server 2025) are affected by the missing ISRG Root X2 CA issue.
> 
> EDITED: It seems even worse that new installation of Windows 11 24H2 doesn't contain any of ISRG Root CA includinding X1 and X2.

And if your server doesn't use let's encrypt at all (such as zerossl), please make sure you have installed the respective CA certificate correctly. The newest Windows images don't have many CA certificates now.

**Comment by zhw618** [comment]
> @zhw618 you need to install it at the _trusted root_ and only _trusted root_. Pure installation doesn't work.
> 
> ![image](https://private-user-images.githubusercontent.com/54673341/385566725-6bb522d4-692c-4074-989a-6be6b4c6123d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NzAxNTMsIm5iZiI6MTczMTQ2OTg1MywicGF0aCI6Ii81NDY3MzM0MS8zODU1NjY3MjUtNmJiNTIyZDQtNjkyYy00MDc0LTk4OWEtNmJlNmI0YzYxMjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAzNTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZDcyOTk2MmYwMDNmNTViNDc0NWYwNDQ4YjA3YjNkZTViM2ZmYmE4Y2ViYWY1YTFhYjQwZDdmM2VhMmZjM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xs_K7_Oribx92f6xRFc6xf05-yZWIPvtQWbWfCnrb0E)
> 
> BTW can you attach the output of `gci Cert:\LocalMachine\Root` at powershell, so we can determine whether it is CA issue. And you can attach the output of naive command which has the correct error number which is used to locate the issue.

Thanks  a lot !  Sorry for late replay
add the output of the  cmd:
~~~bash
PS C:\Users\Administrator> gci Cert:\LocalMachine\Root


   PSParentPath:Microsoft.PowerShell.Security\Certificate::LocalMachine\Root

Thumbprint                                Subject                                                                      
----------                                -------                                                                      
CDD4EEAE6000AC7F40C3802C171E30148030C072  CN=Microsoft Root Certificate Authority, DC=microsoft, DC=com                
BE36A4562FB2EE05DBB3D32323ADF445084ED656  CN=Thawte Timestamping CA, OU=Thawte Certification, O=Thawte, L=Durbanvill...
A43489159A520F0D93D032CCAF37E7FE20A8B419  CN=Microsoft Root Authority, OU=Microsoft Corporation, OU=Copyright (c) 19...
933C6DDEE95C9C41A40F9F50493D82BE03AD87BF  CN=ISRG Root X1, O=Internet Security Research Group, C=US                    
92B46C76E13054E104F230517E6E504D43AB10B5  CN=Symantec Enterprise Mobile Root for Microsoft, O=Symantec Corporation, ...
8F43288AD272F3103B6FB1428485EA3014C0BCFE  CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=R...
870CD241DFE2AE53951BF36E02310EA12E23822E  CN=VMware Inc., C=China                                                      
7F95276D4951499FD756DF344AA24FB38CEAF678  CN=ZeroSSL ECC Domain Secure Site CA, O=ZeroSSL, C=AT                        
7F88CD7223F3C813818C994614A89C99FA3B5247  CN=Microsoft Authenticode(tm) Root Authority, O=MSFT, C=US                   
3B1EFD3A66EA28B16697394703A72CA340A05BD5  CN=Microsoft Root Certificate Authority 2010, O=Microsoft Corporation, L=R...
31F9FC8BA3805986B721EA7295C65B3A44534274  CN=Microsoft ECC TS Root Certificate Authority 2018, O=Microsoft Corporati...
245C97DF7514E7CF2DF8BE72AE957B9E04741E85  OU=Copyright (c) 1997 Microsoft Corp., OU=Microsoft Time Stamping Service ...
1FDE95FFA5474DA56352AE3FEA6D55B1F20158E9  CN=VMware Inc., C=China                                                      
18F7C1FCC3090203FD5BAA2F861A754976C8DD25  OU="NO LIABILITY ACCEPTED, (c)97 VeriSign, Inc.", OU=VeriSign Time Stampin...
06F1AA330B927B753A40E68CDF22E34BCBEF3352  CN=Microsoft ECC Product Root Certificate Authority 2018, O=Microsoft Corp...
0119E81BE9A14CD8E22F40AC118C687ECBA3F4D8  CN=Microsoft Time Stamp Root Certificate Authority 2014, O=Microsoft Corpo...
F40042E2E5F7E8EF8189FED15519AECE42C3BFA2  CN=Microsoft Identity Verification Root Certificate Authority 2020, O=Micr...
DF3C24F9BFD666761B268073FE06D1CC8D4F82A4  CN=DigiCert Global Root G2, OU=www.digicert.com, O=DigiCert Inc, C=US        
DDFB16CD4931C973A2037D3FC83A4D7D775D05E4  CN=DigiCert Trusted Root G4, OU=www.digicert.com, O=DigiCert Inc, C=US       
DAC9024F54D8F6DF94935FB1732638CA6AD77C13  CN=DST Root CA X3, O=Digital Signature Trust Co.                             
D4DE20D05E66FC53FE1A50882C78DB2852CAE474  CN=Baltimore CyberTrust Root, OU=CyberTrust, O=Baltimore, C=IE               
D1EB23A46D17D68FD92564C2F1F1601764D8E349  CN=AAA Certificate Services, O=Comodo CA Limited, L=Salford, S=Greater Man...
CABD2A79A1076A31F21D253635CB039D4329A5E8  CN=ISRG Root X1, O=Internet Security Research Group, C=US                    
BDB1B93CD5978D45C6261455F8DB95C75AD153AF  CN=ISRG Root X2, O=Internet Security Research Group, C=US                    
B1BC968BD4F49D622AA89A81F2150152A41D829C  CN=GlobalSign Root CA, OU=Root CA, O=GlobalSign nv-sa, C=BE                  
AD7E1C28B064EF8F6003402014C3D0E3370EB58A  OU=Starfield Class 2 Certification Authority, O="Starfield Technologies, I...
A8985D3A65E5E5C4B2D7D66D40C6DD2FB19C5436  CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US        
925A8F8D2C6D04E0665F596AFF22D863E8256F3F  CN=Starfield Services Root Certificate Authority - G2, O="Starfield Techno...
8094640EB5A7A1CA119C1FDDD59F810263A7FBD1  CN=GlobalSign, O=GlobalSign, OU=GlobalSign Root CA - R6                      
7E04DE896A3E666D00E687D33FFAD93BE83D349E  CN=DigiCert Global Root G3, OU=www.digicert.com, O=DigiCert Inc, C=US        
742C3192E607E424EB4549542BE1BBC53E6174E2  OU=Class 3 Public Primary Certification Authority, O="VeriSign, Inc.", C=US  
73A5E64A3BFF8316FF0EDCCC618A906E4EAE4D74  CN=Microsoft RSA Root Certificate Authority 2017, O=Microsoft Corporation,...
5FB7EE0633E259DBAD0C4C9AE6D38F1A61C7DC25  CN=DigiCert High Assurance EV Root CA, OU=www.digicert.com, O=DigiCert Inc...
4EFC31460C619ECAE59C1BCE2C008036D94C84B8  CN=GlobalSign Code Signing Root R45, O=GlobalSign nv-sa, C=BE                
4EB6D578499B1CCF5F581EAD56BE3D9B6744A5E5  CN=VeriSign Class 3 Public Primary Certification Authority - G5, OU="(c) 2...
3679CA35668772304D30A5FB873B0FA77BB70D54  CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign,...
2B8F1B57330DBBA2D07A6C51F70EE90DDAB9AD8E  CN=USERTrust RSA Certification Authority, O=The USERTRUST Network, L=Jerse...
0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43  CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US    
~~~

**Comment by zhw618** [comment]
> Keep in mind there are two ISRG CAs. If you have imported ISRG Root X1, you properly need to import the X2 one as well.
> 
> For example, the output of my machine shows ISRG Root X2 is missing.
> 
> ```
> PS C:\Users\HKY> gci Cert:\LocalMachine\Root | findstr  ISRG
> CABD2A79A1076A31F21D253635CB039D4329A5E8  CN=ISRG Root X1, O=Internet Security Research Group, C=US
> ```
> 
> And the output of [yass](https://github.com/Chilledheart/yass) also tells the same story (running under command line `yass.exe -logtostderr`)
> 
> ```
> [7480:1112/191406.017:INFO:asio_ssl.cpp(716)] Missing ISRG Root X2 CA
> ```

still  not work  :( . 

Attach the output of yass ,  Thanks!
~~~bash
D:\_v2ray\yass-win7\yass-mingw-win7-1.16.0>yass -logtostderr

D:\_v2ray\yass-win7\yass-mingw-win7-1.16.0>attached to parent process' console
Application starting: 1.16.0 type: gui client (windows)
Last Change: dbb7c7b6ab3ac56984a4b2aac4bb5ae28098dfbc-refs/branch-heads/1.16.0{0}
Features: official-build;mingw;arch: x86_64;release;clang 20.0.0;crosscompile;linker lld;ldflags icf;win7;sse3;libc++;mingw ucrt;tcmalloc_minimal (dll);mbedtls;ca-certificates 20240203.3.98;jsoncpp;zlib;c-ares;nghttp2;quiche;balsa http parser
TCMALLOC: gperftools 2.15
using option from registry
The key existed and was simply opened without being changed: HKEY_CURRENT_USER/SOFTWARE\YetAnotherShadowSocket
opened config
bad field: server
failed to load option server
bad field: server_port
failed to load option server_port
bad field: method
failed to load option method
bad field: username
failed to load option username
bad field: password
failed to load option password
bad field: local
failed to load option local
bad field: local_port
failed to load option local_port
bad field: server_sni
failed to load option server_sni
bad field: fast_open
failed to load option fast_open
bad field: fast_open_connect
failed to load option fast_open_connect
bad field: doh_url
failed to load option doh_url
bad field: dot_host
failed to load option dot_host
bad field: connect_timeout
failed to load option connect_timeout
bad field: tcp_nodelay
failed to load option tcp_nodelay
bad field: limit_rate
failed to load option limit_rate
bad field: tcp_keep_alive
failed to load option tcp_keep_alive
bad field: tcp_keep_alive_cnt
failed to load option tcp_keep_alive_cnt
bad field: tcp_keep_alive_idle_timeout
failed to load option tcp_keep_alive_idle_timeout
bad field: tcp_keep_alive_interval
failed to load option tcp_keep_alive_interval
bad field: tcp_congestion_algorithm
failed to load option tcp_congestion_algorithm
bad field: cacert
failed to load option cacert
bad field: capath
failed to load option capath
bad field: certificate_chain_file
failed to load option certificate_chain_file
bad field: insecure_mode
failed to load option insecure_mode
bad field: enable_post_quantum_kyber
failed to load option enable_post_quantum_kyber
bad field: tls13_early_data
failed to load option tls13_early_data
closed config
[1832:1113/125647.018:WARNING:config_version.cpp(130)] Application starting: 1.16.0 type: gui client (windows)
[1832:1113/125647.018:WARNING:config_version.cpp(131)] Last Change: dbb7c7b6ab3ac56984a4b2aac4bb5ae28098dfbc-refs/branch-heads/1.16.0{0}
[1832:1113/125647.018:WARNING:config_version.cpp(132)] Features: official-build;mingw;arch: x86_64;release;clang 20.0.0;crosscompile;linker lld;ldflags icf;win7;sse3;libc++;mingw ucrt;tcmalloc_minimal (dll);mbedtls;ca-certificates 20240203.3.98;jsoncpp;zlib;c-ares;nghttp2;quiche;balsa http parser
[1832:1113/125647.018:WARNING:config_version.cpp(134)] TCMALLOC: gperftools 2.15
[260:1113/125647.019:INFO:cli_worker.cpp(170)] worker: background thread started
[1832:1113/125647.091:WARNING:yass_frame.cpp(127)] detected locale : simplified chinese
[1832:1113/125647.095:WARNING:yass_frame.cpp(825)] Adjust layout to Dpi: 120
[260:1113/125804.499:INFO:c-ares.cpp(141)] C-Ares Loaded
[260:1113/125805.283:INFO:cli_worker.cpp(228)] worker: resolved server ips: 67.230.162.109
[260:1113/125805.283:INFO:cli_worker.cpp(261)] worker: resolved local ips: 127.0.0.1
[260:1113/125805.289:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /DC=com/DC=microsoft/CN=Microsoft Root Certificate Authority
[260:1113/125805.289:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /C=ZA/ST=Western Cape/L=Durbanville/O=Thawte/OU=Thawte Certification/CN=Thawte Timestamping CA
[260:1113/125805.289:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /OU=Copyright (c) 1997 Microsoft Corp./OU=Microsoft Corporation/CN=Microsoft Root Authority
[260:1113/125805.289:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /C=US/O=Internet Security Research Group/CN=ISRG Root X1
[260:1113/125805.289:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /C=US/O=MSFT/CN=Microsoft Authenticode(tm) Root Authority
[260:1113/125805.289:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /O=Microsoft Trust Network/OU=Microsoft Corporation/OU=Microsoft Time Stamping Service Root/OU=Copyright (c) 1997 Microsoft Corp.
[260:1113/125805.289:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /O=VeriSign Trust Network/OU=VeriSign, Inc./OU=VeriSign Time Stamping Service Root/OU=NO LIABILITY ACCEPTED, (c)97 VeriSign, Inc.
[260:1113/125805.289:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /O=Digital Signature Trust Co./CN=DST Root CA X3
[260:1113/125805.289:INFO:asio_ssl.cpp(546)] Loaded ca from SChannel: 30 certificates
[260:1113/125805.289:INFO:content_server.hpp(158)] Listening (client) on 127.0.0.1:10808
[260:1113/125805.289:INFO:cli_worker.cpp(288)] worker: tcp server listening at 127.0.0.1:10808
using option from registry
The key existed and was simply opened without being changed: HKEY_CURRENT_USER/SOFTWARE\YetAnotherShadowSocket
opened config
saved option server: zhw.home.kg
saved option server_sni: naive-zhw
saved option server_port: 18443
saved option method: https
saved option username: zhw
saved option password: ***
saved option local: 127.0.0.1
saved option local_port: 10808
saved option fast_open: false
saved option fast_open_connect: false
saved option doh_url: (nil)
saved option dot_host: (nil)
saved option timeout: 0
saved option connect_timeout: 0
saved option tcp_nodelay: true
saved option limit_rate: 0m
saved option tcp_keep_alive: true
saved option tcp_keep_alive_cnt: 9
saved option tcp_keep_alive_idle_timeout: 7200
saved option tcp_keep_alive_interval: 75
saved option tcp_congestion_algorithm: (nil)
saved option cacert: (nil)
saved option capath: (nil)
saved option certificate_chain_file: (nil)
saved option insecure_mode: false
saved option enable_post_quantum_kyber: false
saved option tls13_early_data: true
closed config
[260:1113/125848.688:INFO:cli_connection.cpp(2054)] Connection (client) 1 connect ntp.msn.cn:443
[260:1113/125848.689:INFO:cli_connection.cpp(2054)] Connection (client) 2 connect assets.msn.cn:443
[260:1113/125848.702:INFO:cli_connection.cpp(2054)] Connection (client) 3 connect ts2.cn.mm.bing.net:443
[260:1113/125848.703:INFO:cli_connection.cpp(2054)] Connection (client) 4 connect www.bing.com:443
[260:1113/125848.704:INFO:cli_connection.cpp(2054)] Connection (client) 5 connect browser.events.data.msn.cn:443
[260:1113/125848.705:INFO:cli_connection.cpp(2054)] Connection (client) 6 connect img-s.msn.cn:443
[260:1113/125848.768:INFO:cli_connection.cpp(2054)] Connection (client) 7 connect assets.msn.cn:443
[260:1113/125848.854:INFO:cli_connection.cpp(2054)] Connection (client) 8 connect edge.microsoft.com:443
[260:1113/125849.010:INFO:cli_connection.cpp(2054)] Connection (client) 9 connect ts2.cn.mm.bing.net:443
[260:1113/125849.010:INFO:cli_connection.cpp(2054)] Connection (client) 10 connect ts2.cn.mm.bing.net:443
[260:1113/125849.010:INFO:cli_connection.cpp(2054)] Connection (client) 11 connect browser.events.data.msn.cn:443
[260:1113/125849.010:INFO:cli_connection.cpp(2054)] Connection (client) 12 connect browser.events.data.msn.cn:443
[260:1113/125849.010:INFO:cli_connection.cpp(2054)] Connection (client) 13 connect browser.events.data.msn.cn:443
[260:1113/125849.010:INFO:cli_connection.cpp(2054)] Connection (client) 14 connect browser.events.data.msn.cn:443
~~~

**Comment by Chilledheart** [comment]
Check if your server allows your port to be connected:

![image](https://github.com/user-attachments/assets/473af23f-e012-445b-8d11-d5ab28c62e8a)

**Comment by Chilledheart** [comment]
![image](https://github.com/user-attachments/assets/03f93845-e930-4bea-8528-51f86c155fce)

You have ISRG Root X1 installed, so your problem is resolved. Check your configuration.

**Comment by Chilledheart** [comment]
And don't use server_sni, just leave it alone (empty) if you know nothing about it.

**Comment by zhw618** [comment]
> And don't use server_sni(服务器名称指示), just leave it alone (empty) if you know nothing about it.

I leave the server_sni keep blank , now the log as follows, but still not works~~~555
~~~cmd
D:\_v2ray\yass-win7\yass-mingw-win7-1.16.0>yass -logtostderr

D:\_v2ray\yass-win7\yass-mingw-win7-1.16.0>attached to parent process' console
Application starting: 1.16.0 type: gui client (windows)
Last Change: dbb7c7b6ab3ac56984a4b2aac4bb5ae28098dfbc-refs/branch-heads/1.16.0{0}
Features: official-build;mingw;arch: x86_64;release;clang 20.0.0;crosscompile;linker lld;ldflags icf;win7;sse3;libc++;mingw ucrt;tcmalloc_minimal (dll);mbedtls;ca-certificates 20240203.3.98;jsoncpp;zlib;c-ares;nghttp2;quiche;balsa http parser
TCMALLOC: gperftools 2.15
using option from registry
The key existed and was simply opened without being changed: HKEY_CURRENT_USER/SOFTWARE\YetAnotherShadowSocket
opened config
loaded option server: zhw.home.kg
loaded option server_port: 18443
loaded option method: https
loaded option username: zhw
loaded option password: ***
loaded option local: 127.0.0.1
loaded option local_port: 10808
loaded option server_sni: (nil)
loaded option fast_open: false
loaded option fast_open_connect: false
loaded option doh_url: (nil)
loaded option dot_host: (nil)
loaded option connect_timeout: 0
loaded option tcp_nodelay: true
loaded option limit_rate: 0m
loaded option tcp_keep_alive: true
loaded option tcp_keep_alive_cnt: 9
loaded option tcp_keep_alive_idle_timeout: 7200
loaded option tcp_keep_alive_interval: 75
loaded option tcp_congestion_algorithm: (nil)
loaded option cacert: (nil)
loaded option capath: (nil)
loaded option certificate_chain_file: (nil)
loaded option insecure_mode: false
loaded option enable_post_quantum_kyber: false
loaded option tls13_early_data: true
closed config
[3732:1113/225948.704:WARNING:config_version.cpp(130)] Application starting: 1.16.0 type: gui client (windows)
[3732:1113/225948.704:WARNING:config_version.cpp(131)] Last Change: dbb7c7b6ab3ac56984a4b2aac4bb5ae28098dfbc-refs/branch-heads/1.16.0{0}
[3732:1113/225948.707:WARNING:config_version.cpp(132)] Features: official-build;mingw;arch: x86_64;release;clang 20.0.0;crosscompile;linker lld;ldflags icf;win7;sse3;libc++;mingw ucrt;tcmalloc_minimal (dll);mbedtls;ca-certificates 20240203.3.98;jsoncpp;zlib;c-ares;nghttp2;quiche;balsa http parser
[3732:1113/225948.708:WARNING:config_version.cpp(134)] TCMALLOC: gperftools 2.15
[3828:1113/225948.708:INFO:cli_worker.cpp(170)] worker: background thread started
[3732:1113/225948.816:WARNING:yass_frame.cpp(127)] detected locale : simplified chinese
[3732:1113/225948.825:WARNING:yass_frame.cpp(825)] Adjust layout to Dpi: 144
[3828:1113/225950.760:INFO:c-ares.cpp(141)] C-Ares Loaded
[3828:1113/225951.171:INFO:cli_worker.cpp(228)] worker: resolved server ips: 67.230.162.109
[3828:1113/225951.171:INFO:cli_worker.cpp(261)] worker: resolved local ips: 127.0.0.1
[3828:1113/225951.182:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /DC=com/DC=microsoft/CN=Microsoft Root Certificate Authority
[3828:1113/225951.182:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /C=ZA/ST=Western Cape/L=Durbanville/O=Thawte/OU=Thawte Certification/CN=Thawte Timestamping CA
[3828:1113/225951.182:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /OU=Copyright (c) 1997 Microsoft Corp./OU=Microsoft Corporation/CN=Microsoft Root Authority
[3828:1113/225951.182:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /C=US/O=MSFT/CN=Microsoft Authenticode(tm) Root Authority
[3828:1113/225951.185:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /O=Microsoft Trust Network/OU=Microsoft Corporation/OU=Microsoft Time Stamping Service Root/OU=Copyright (c) 1997 Microsoft Corp.
[3828:1113/225951.185:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /O=VeriSign Trust Network/OU=VeriSign, Inc./OU=VeriSign Time Stamping Service Root/OU=NO LIABILITY ACCEPTED, (c)97 VeriSign, Inc.
[3828:1113/225951.185:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /O=Digital Signature Trust Co./CN=DST Root CA X3
[3828:1113/225951.185:INFO:asio_ssl.cpp(546)] Loaded ca from SChannel: 30 certificates
[3828:1113/225951.185:INFO:content_server.hpp(158)] Listening (client) on 127.0.0.1:10808
[3828:1113/225951.185:INFO:cli_worker.cpp(288)] worker: tcp server listening at 127.0.0.1:10808
using option from registry
The key existed and was simply opened without being changed: HKEY_CURRENT_USER/SOFTWARE\YetAnotherShadowSocket
opened config
saved option server: zhw.home.kg
saved option server_sni: (nil)
saved option server_port: 18443
saved option method: https
saved option username: zhw
saved option password: ***
saved option local: 127.0.0.1
saved option local_port: 10808
saved option fast_open: false
saved option fast_open_connect: false
saved option doh_url: (nil)
saved option dot_host: (nil)
saved option timeout: 0
saved option connect_timeout: 0
saved option tcp_nodelay: true
saved option limit_rate: 0m
saved option tcp_keep_alive: true
saved option tcp_keep_alive_cnt: 9
saved option tcp_keep_alive_idle_timeout: 7200
saved option tcp_keep_alive_interval: 75
saved option tcp_congestion_algorithm: (nil)
saved option cacert: (nil)
saved option capath: (nil)
saved option certificate_chain_file: (nil)
saved option insecure_mode: false
saved option enable_post_quantum_kyber: false
saved option tls13_early_data: true
closed config
[3828:1113/230004.046:INFO:cli_connection.cpp(2054)] Connection (client) 1 connect www.google.com:443
[3828:1113/230004.048:INFO:cli_connection.cpp(2054)] Connection (client) 2 connect www.gstatic.com:443
[3828:1113/230027.524:INFO:cli_connection.cpp(2054)] Connection (client) 3 connect edge.microsoft.com:443
[3828:1113/230034.042:INFO:cli_connection.cpp(2142)] Connection (client) 1 closed: End of file value: 2
[3828:1113/230034.042:INFO:cli_connection.cpp(2142)] Connection (client) 2 closed: End of file value: 2
[3828:1113/230034.053:INFO:cli_connection.cpp(2054)] Connection (client) 4 connect edge-http.microsoft.com:80
[3828:1113/230053.517:INFO:cli_connection.cpp(2054)] Connection (client) 5 connect cn.bing.com:443
[3828:1113/230057.523:INFO:cli_connection.cpp(2142)] Connection (client) 3 closed: End of file value: 2
[3828:1113/230104.058:INFO:cli_connection.cpp(2142)] Connection (client) 4 closed: End of file value: 2
[3828:1113/230123.524:INFO:cli_connection.cpp(2142)] Connection (client) 5 closed: End of file value: 2

~~~

**Comment by Chilledheart** [comment]
> I spent an hour formatting the C drive, reinstalling Server 2025 Datacenter Edition, and updating it to version 26100.2161. I only installed the network card driver, and the first thing I did was retest NaiveProxy. It’s working perfectly! It’s truly amazing~~ I’m not sure what the issue was before, but anyway, thanks to everyone for your help! Thank you.

Nice to see that. But you'd better re-check with "gci Cert:\LocalMachine\Root | findstr  ISRG" in powershell after upgrading. 

As far as I can tell, naive is affected by missing ISRG Root X1/X2/GTS but the windows will install ISRG Root X1 __automatically__ when you open that website on edge.

For my case,
(Before open the website of https://letsencrypt.org in edge)
![image](https://github.com/user-attachments/assets/f337dceb-3d10-437a-8d7a-6ddc3d38b756)

(After open the website of https://letsencrypt.org in edge)
![image](https://github.com/user-attachments/assets/84f990a2-ff17-41d5-9bf8-a1d18c4cf888)

(After open the website of https://zerossl.com in edge)
![image](https://github.com/user-attachments/assets/10aeaaeb-ca2a-4d41-ab49-75b035b4a739)

**Comment by Chilledheart** [comment]
I see. ISRG Root X1 and other missing CAs exist on _AuthRoot_ but not _Root_ when it boots.

![image](https://github.com/user-attachments/assets/370b1d18-68c4-46e9-aab8-b163bef3205f)

**Comment by Chilledheart** [comment]
@zhw618 Please close this issue if your problem is resolved.

**Comment by zhw618** [comment]
> @zhw618 Please close this issue if your problem is resolved.

Thanks！

But today I installed some other software, and then this issue appeared again...  :----(
I’m troubleshooting it~~~

**Comment by zhw618** [comment]
> > I spent an hour formatting the C drive, reinstalling Server 2025 Datacenter Edition, and updating it to version 26100.2161. I only installed the network card driver, and the first thing I did was retest NaiveProxy. It’s working perfectly! It’s truly amazing~~ I’m not sure what the issue was before, but anyway, thanks to everyone for your help! Thank you.
> 
> Nice to see that. But you'd better re-check with "gci Cert:\LocalMachine\Root | findstr ISRG" in powershell after upgrading.
> 
after reinstall win 2025, Brand new condition Windows 2025 (drivers only installed)，  naive/ yass works well, 
the output  of above command is  as follow: （Hope these are helpful to you.）

~~~cmd
PS C:\Users\Administrator> gci Cert:\LocalMachine\Root | findstr ISRG
PS C:\Users\Administrator>
~~~
~~~cmd
PS C:\Users\Administrator> gci Cert:\LocalMachine\CA

   PSParentPath:Microsoft.PowerShell.Security\Certificate::LocalMachine\CA

Thumbprint                                Subject
----------                                -------
FEE449EE0E3965A5246F000E87FDE2A065FD89D4  CN=Root Agency
D559A586669B08F46A30A133F8A9ED3D038E2EA8  OU=www.verisign.com/CPS Incorp.by Ref. LIABILITY LTD.(c)97 VeriSign, OU=Ve...
D4FFDB19BA590FFFAA34DB5F4B568706A2978436  CN=Microsoft TPM Root Certificate Authority 2014, O=Microsoft Corporation,...
1EA340237FC4CA6A6AA12CEE2B0562D41BA99963  CN=INTC-KEYID-6B773F7FC8EAF6A5B10D7361BF2013D128D03846
109F1CAED645BB78B3EA2B94C0697C740733031C  CN=Microsoft Windows Hardware Compatibility, OU=Microsoft Corporation, OU=...
~~~

~~~cmd
PS C:\Users\Administrator> gci Cert:\LocalMachine\AuthRoot

   PSParentPath:Microsoft.PowerShell.Security\Certificate::LocalMachine\AuthRoot

Thumbprint                                Subject
----------                                -------
F40042E2E5F7E8EF8189FED15519AECE42C3BFA2  CN=Microsoft Identity Verification Root Certificate Authority 2020, O=Micr...
DF3C24F9BFD666761B268073FE06D1CC8D4F82A4  CN=DigiCert Global Root G2, OU=www.digicert.com, O=DigiCert Inc, C=US
DDFB16CD4931C973A2037D3FC83A4D7D775D05E4  CN=DigiCert Trusted Root G4, OU=www.digicert.com, O=DigiCert Inc, C=US
D69B561148F01C77C54578C10926DF5B856976AD  CN=GlobalSign, O=GlobalSign, OU=GlobalSign Root CA - R3
D1EB23A46D17D68FD92564C2F1F1601764D8E349  CN=AAA Certificate Services, O=Comodo CA Limited, L=Salford, S=Greater Man...
A8985D3A65E5E5C4B2D7D66D40C6DD2FB19C5436  CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
925A8F8D2C6D04E0665F596AFF22D863E8256F3F  CN=Starfield Services Root Certificate Authority - G2, O="Starfield Techno...
7E04DE896A3E666D00E687D33FFAD93BE83D349E  CN=DigiCert Global Root G3, OU=www.digicert.com, O=DigiCert Inc, C=US
742C3192E607E424EB4549542BE1BBC53E6174E2  OU=Class 3 Public Primary Certification Authority, O="VeriSign, Inc.", C=US
73A5E64A3BFF8316FF0EDCCC618A906E4EAE4D74  CN=Microsoft RSA Root Certificate Authority 2017, O=Microsoft Corporation,...
4EFC31460C619ECAE59C1BCE2C008036D94C84B8  CN=GlobalSign Code Signing Root R45, O=GlobalSign nv-sa, C=BE
2B8F1B57330DBBA2D07A6C51F70EE90DDAB9AD8E  CN=USERTrust RSA Certification Authority, O=The USERTRUST Network, L=Jerse...
0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43  CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US


~~~

**Comment by Chilledheart** [comment]
It is too bad. I still need to figure out why ISRG X1 Root is missing.

**Comment by Chilledheart** [comment]
I still insist that you need to import these CA including ISRG X1 Root/GTS4 somehow.

(after fresh installation)

![image](https://github.com/user-attachments/assets/78ccdb11-2ed3-4af5-b7f2-1ac46b50eaed)

(Connection 1: no such CA imported)
(Connection 2:CA imoprted)

**Comment by Chilledheart** [comment]
For missing ISRG X1 Root.

![image](https://github.com/user-attachments/assets/4f90a2aa-d6e0-47f9-a464-83386ddad309)

**Comment by Chilledheart** [comment]
For yass (missing GTS 4, zerossl.org), the output is like something like below:

![image](https://github.com/user-attachments/assets/b4078be8-9542-4948-8e16-ccf16024424a)

**Comment by Chilledheart** [comment]
You can compare naive/yass's output with the output above to see if you have the same issue.

**Comment by Chilledheart** [comment]
I don't know if @klzgrad is acknowledged with this issue (https://github.com/klzgrad/naiveproxy/issues/685#issuecomment-2475391131 and  https://github.com/klzgrad/naiveproxy/issues/685#issuecomment-2475391131) but it will be fixed in yass's next release (for zerossl.org support). If you're using let'sencrypt.org's certificate, then it has been fixed in current yass.

**Comment by zhw618** [comment]
fresh win 2025,  naive works well , the outputs :
~~~
PS D:\_v2ray\NaiveProxy_bin> gci Cert:\LocalMachine\Root | findstr ISRG
PS D:\_v2ray\NaiveProxy_bin>
PS D:\_v2ray\NaiveProxy_bin> .\naive.exe .\config_letsEncrypt.json
[1114/124917.732:INFO:naive_proxy_bin.cc(217)] Proxying via HTTPS zhw.home.kg:18443
[1114/124917.734:INFO:naive_proxy_bin.cc(479)] Listening on socks://127.0.0.1:10808
[1114/124921.466:INFO:naive_connection.cc(277)] Connection 1 to www.bing.com:443
[1114/124921.873:INFO:naive_connection.cc(277)] Connection 2 to github.com:443
[1114/124921.875:INFO:naive_connection.cc(277)] Connection 3 to github.githubassets.com:443
[1114/124921.961:INFO:naive_proxy_delegate.cc(154)] https://zhw.home.kg:18443 negotiated padding type: Variant1
[1114/124922.421:INFO:naive_connection.cc(277)] Connection 4 to raw.githubusercontent.com:443
[1114/124922.462:INFO:naive_connection.cc(277)] Connection 5 to alive.github.com:443
[1114/124923.244:INFO:naive_proxy.cc(185)] Connection 5 closed: OK
~~~

then  I  imported  ISRG,  the  outputs are :
~~~
PS D:\_v2ray\NaiveProxy_bin> gci Cert:\LocalMachine\Root | findstr ISRG
CABD2A79A1076A31F21D253635CB039D4329A5E8  CN=ISRG Root X1, O=Internet Security Research Group, C=US
PS D:\_v2ray\NaiveProxy_bin> .\naive.exe .\config_letsEncrypt.json
[1114/125311.799:INFO:naive_proxy_bin.cc(217)] Proxying via HTTPS zhw.home.kg:18443
[1114/125311.800:INFO:naive_proxy_bin.cc(479)] Listening on socks://127.0.0.1:10808
[1114/125315.317:INFO:naive_connection.cc(277)] Connection 1 to www.google.com:443
[1114/125315.748:INFO:naive_proxy_delegate.cc(154)] https://zhw.home.kg:18443 negotiated padding type: Variant1
[1114/125317.095:INFO:naive_connection.cc(277)] Connection 2 to ogads-pa.googleapis.com:443
[1114/125318.082:INFO:naive_connection.cc(277)] Connection 3 to play.google.com:443
PS D:\_v2ray\NaiveProxy_bin>
PS D:\_v2ray\NaiveProxy_bin>
~~~

the outputs of  yass (fresh win2025, works well) :
~~~
PS D:\_v2ray\yass-win7\yass-mingw-win7-1.16.0> gci Cert:\LocalMachine\Root | findstr ISRG
CABD2A79A1076A31F21D253635CB039D4329A5E8  CN=ISRG Root X1, O=Internet Security Research Group, C=US
PS D:\_v2ray\yass-win7\yass-mingw-win7-1.16.0>
PS D:\_v2ray\yass-win7\yass-mingw-win7-1.16.0> .\yass.exe  -logtostderr
PS D:\_v2ray\yass-win7\yass-mingw-win7-1.16.0> attached to parent process' console
Application starting: 1.16.0 type: gui client (windows)
Last Change: dbb7c7b6ab3ac56984a4b2aac4bb5ae28098dfbc-refs/branch-heads/1.16.0{0}
Features: official-build;mingw;arch: x86_64;release;clang 20.0.0;crosscompile;linker lld;ldflags icf;win7;sse3;libc++;mingw ucrt;tcmalloc_minimal (dll);mbedtls;ca-certificates 20240203.3.98;jsoncpp;zlib;c-ares;nghttp2;quiche;balsa http parser
TCMALLOC: gperftools 2.15
using option from registry
The key existed and was simply opened without being changed: HKEY_CURRENT_USER/SOFTWARE\YetAnotherShadowSocket
opened config
loaded option server: zhw.home.kg
loaded option server_port: 18443
loaded option method: http2
loaded option username: zhw
loaded option password: ***
loaded option local: 127.0.0.1
loaded option local_port: 10808
loaded option server_sni: naive-zhw
loaded option fast_open: false
loaded option fast_open_connect: false
loaded option doh_url: (nil)
loaded option dot_host: (nil)
loaded option connect_timeout: 0
loaded option tcp_nodelay: true
loaded option limit_rate: 0m
loaded option tcp_keep_alive: true
loaded option tcp_keep_alive_cnt: 9
loaded option tcp_keep_alive_idle_timeout: 7200
loaded option tcp_keep_alive_interval: 75
loaded option tcp_congestion_algorithm: (nil)
loaded option cacert: (nil)
loaded option capath: (nil)
loaded option certificate_chain_file: (nil)
loaded option insecure_mode: false
loaded option enable_post_quantum_kyber: true
loaded option tls13_early_data: true
closed config
[6940:1114/130343.154:WARNING:config_version.cpp(130)] Application starting: 1.16.0 type: gui client (windows)
[6940:1114/130343.154:WARNING:config_version.cpp(131)] Last Change: dbb7c7b6ab3ac56984a4b2aac4bb5ae28098dfbc-refs/branch-heads/1.16.0{0}
[6940:1114/130343.154:WARNING:config_version.cpp(132)] Features: official-build;mingw;arch: x86_64;release;clang 20.0.0;crosscompile;linker lld;ldflags icf;win7;sse3;libc++;mingw ucrt;tcmalloc_minimal (dll);mbedtls;ca-certificates 20240203.3.98;jsoncpp;zlib;c-ares;nghttp2;quiche;balsa http parser
[6940:1114/130343.154:WARNING:config_version.cpp(134)] TCMALLOC: gperftools 2.15
[8332:1114/130343.154:INFO:cli_worker.cpp(170)] worker: background thread started
[6940:1114/130343.225:WARNING:yass_frame.cpp(127)] detected locale : simplified chinese
[6940:1114/130343.247:WARNING:yass_frame.cpp(825)] Adjust layout to Dpi: 120
[8332:1114/130351.352:INFO:c-ares.cpp(141)] C-Ares Loaded
[8332:1114/130351.364:INFO:cli_worker.cpp(228)] worker: resolved server ips: 67.230.162.109
[8332:1114/130351.364:INFO:cli_worker.cpp(261)] worker: resolved local ips: 127.0.0.1
[8332:1114/130351.370:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /DC=com/DC=microsoft/CN=Microsoft Root Certificate Authority
[8332:1114/130351.370:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /C=ZA/ST=Western Cape/L=Durbanville/O=Thawte/OU=Thawte Certification/CN=Thawte Timestamping CA
[8332:1114/130351.370:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /OU=Copyright (c) 1997 Microsoft Corp./OU=Microsoft Corporation/CN=Microsoft Root Authority
[8332:1114/130351.370:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /C=US/O=MSFT/CN=Microsoft Authenticode(tm) Root Authority
[8332:1114/130351.370:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /O=Microsoft Trust Network/OU=Microsoft Corporation/OU=Microsoft Time Stamping Service Root/OU=Copyright (c) 1997 Microsoft Corp.
[8332:1114/130351.370:WARNING:asio_ssl.cpp(308)] Ignore inactive cert: /O=VeriSign Trust Network/OU=VeriSign, Inc./OU=VeriSign Time Stamping Service Root/OU=NO LIABILITY ACCEPTED, (c)97 VeriSign, Inc.
[8332:1114/130351.377:INFO:asio_ssl.cpp(546)] Loaded ca from SChannel: 24 certificates
[8332:1114/130351.377:INFO:asio_ssl.cpp(716)] Missing ISRG Root X2 CA
[8332:1114/130351.378:INFO:asio_ssl.cpp(724)] Loaded supplementary ca bundle with 3 certificates
[8332:1114/130351.378:INFO:content_server.hpp(158)] Listening (client) on 127.0.0.1:10808
[8332:1114/130351.378:INFO:cli_worker.cpp(288)] worker: tcp server listening at 127.0.0.1:10808
using option from registry
The key existed and was simply opened without being changed: HKEY_CURRENT_USER/SOFTWARE\YetAnotherShadowSocket
opened config
saved option server: zhw.home.kg
saved option server_sni: (nil)
saved option server_port: 18443
saved option method: http2
saved option username: zhw
saved option password: ***
saved option local: 127.0.0.1
saved option local_port: 10808
saved option fast_open: false
saved option fast_open_connect: false
saved option doh_url: (nil)
saved option dot_host: (nil)
saved option timeout: 0
saved option connect_timeout: 0
saved option tcp_nodelay: true
saved option limit_rate: 0m
saved option tcp_keep_alive: true
saved option tcp_keep_alive_cnt: 9
saved option tcp_keep_alive_idle_timeout: 7200
saved option tcp_keep_alive_interval: 75
saved option tcp_congestion_algorithm: (nil)
saved option cacert: (nil)
saved option capath: (nil)
saved option certificate_chain_file: (nil)
saved option insecure_mode: false
saved option enable_post_quantum_kyber: true
saved option tls13_early_data: true
closed config
[8332:1114/130417.099:INFO:cli_connection.cpp(2054)] Connection (client) 1 connect collector.github.com:443
[8332:1114/130417.534:INFO:cli_connection.cpp(270)] Connection (client) 1 for collector.github.com:443 Padding support enabled Backed by Caddy.
[8332:1114/130417.697:INFO:cli_connection.cpp(2054)] Connection (client) 2 connect raw.githubusercontent.com:443
[8332:1114/130418.111:INFO:cli_connection.cpp(270)] Connection (client) 2 for raw.githubusercontent.com:443 Padding support enabled Backed by Caddy.
[8332:1114/130418.678:INFO:cli_connection.cpp(2054)] Connection (client) 3 connect www.google.com:443
[8332:1114/130418.680:INFO:cli_connection.cpp(2054)] Connection (client) 4 connect www.gstatic.com:443
[8332:1114/130419.095:INFO:cli_connection.cpp(270)] Connection (client) 3 for www.google.com:443 Padding support enabled Backed by Caddy.
[8332:1114/130419.099:INFO:cli_connection.cpp(270)] Connection (client) 4 for www.gstatic.com:443 Padding support enabled Backed by Caddy.
[8332:1114/130419.568:INFO:cli_connection.cpp(2054)] Connection (client) 5 connect ogads-pa.googleapis.com:443
[8332:1114/130419.975:INFO:cli_connection.cpp(270)] Connection (client) 5 for ogads-pa.googleapis.com:443 Padding support enabled Backed by Caddy.
[8332:1114/130420.793:INFO:cli_connection.cpp(2054)] Connection (client) 6 connect play.google.com:443
[8332:1114/130421.202:INFO:cli_connection.cpp(270)] Connection (client) 6 for play.google.com:443 Padding support enabled Backed by Caddy.
......
~~~

**Comment by Chilledheart** [comment]
> fresh win 2025, naive works well , the outputs :
> 
> ```
> PS D:\_v2ray\NaiveProxy_bin> gci Cert:\LocalMachine\Root | findstr ISRG
> PS D:\_v2ray\NaiveProxy_bin>

You need to check four places:
```
gci Cert:\LocalMachine\Root | findstr ISRG
gci Cert:\LocalMachine\AuthRoot | findstr ISRG
gci Cert:\CurrentUser\Root | findstr ISRG
gci Cert:\CurrentUser\Root | findstr ISRG
```

I suspect there are some undocumented issue related because I found out that we can run ``curl -I https://letsencrypt.org`` without ISRG Root X1 installed.

**Comment by Chilledheart** [comment]
And you can check intermediate CA instead of root CA. chrome browser and naive allows intermediate CA, so it can skip checking ISRG Root X1. see https://www.cnblogs.com/sslwork/p/5986985.html

**Comment by Chilledheart** [comment]
“例如：一个服务器证书 domain.com，是由Intermedia CA签发，而Intermedia CA的颁发者Root CA在WEB浏览器可信CA列表中，则证书的信任链如下：

证书 1 - 使用者：domain.com；颁发者：Intermedia CA

证书 2 - 使用者：Intermedia CA；颁发者： Root CA

证书 3 - 使用者：Root CA ； 办法和： Root CA

当Web浏览器验证到证书3：Root CA时，发现是一个可信CA，则完成验证，允许建立可信连接。当然有些情况下，Intermedia CA也在可信CA列表中，这个时候，就可以直接完成验证，建立可信连接。
”

**Comment by Chilledheart** [comment]
You get find immediate certificate's name like below:

1. Your site and site letsencrypt.org 's immediate certificate is E5 from ISRG Root X1. You can get the same result by clicking  the "Lock" button at browser's address edit.

<img width="423" alt="截屏2024-11-14 17 41 42" src="https://github.com/user-attachments/assets/59b2b3fb-64b0-4340-8ab3-59402ffa7a33">


<img width="542" alt="截屏2024-11-14 17 37 25" src="https://github.com/user-attachments/assets/9ca2b27c-6243-4d39-86d1-012cd973d8e8">

2. To find if E5 has been added in Windows' immediate CA chain, run:
```
gci Cert:\CurrentUser\CA | findstr E5
```

<img width="688" alt="截屏2024-11-14 17 35 53" src="https://github.com/user-attachments/assets/1b58a7bc-6154-419b-8595-eca0eaa75b45">

3. naive should be working if Step 2 is okay

**Comment by Chilledheart** [comment]
And due to yass' limitation, it needs to be restart to reload to reflect those certificate changes but for chrome, edge and naive it doesn't.

**Comment by zhw618** [comment]
> > fresh win 2025, naive works well , the outputs :
> > ```
> > PS D:\_v2ray\NaiveProxy_bin> gci Cert:\LocalMachine\Root | findstr ISRG
> > PS D:\_v2ray\NaiveProxy_bin>
> > ```
> 
> You need to check four places:
> 
> ```
> gci Cert:\LocalMachine\Root | findstr ISRG
> gci Cert:\LocalMachine\AuthRoot | findstr ISRG
> gci Cert:\CurrentUser\Root | findstr ISRG
> gci Cert:\CurrentUser\AuthRoot | findstr ISRG
> ```
> 
> I suspect there are some undocumented issue related because I found out that we can run `curl -I https://letsencrypt.org` without ISRG Root X1 installed.

now  naive/yass  works well, the outputs :
![output](https://github.com/user-attachments/assets/adf3b8a8-975d-4450-8717-5f9bc0234f84)

**Comment by zhw618** [comment]
> > @zhw618 Please close this issue if your problem is resolved.
> 
> Thanks！
> 
> But today I installed some other software, and then this issue appeared again... :----( I’m troubleshooting it~~~

I found the  problem!
if  BBR2  Enabe, naive/ yass will not work~~~
![{D1A2A44A-AA3C-4B81-BCF1-982B1A5B93EB}](https://github.com/user-attachments/assets/d003f3e9-d502-4c1c-a5e0-5bacf12cafc3)

**Comment by Chilledheart** [comment]
It seems an issue with windows 11 24h2

https://bbs.pcbeta.com/viewthread-2016967-1-1.html

**Comment by Chilledheart** [comment]
And I can confirm bbr2 doesn't matter if you are visiting http1.1 site(without https, such as http://www.google.com not https://www.google.com). 

For https website, Client Hello is sent  correctly but naive/yass can receives Servel Hello and but it fails to redirect it to final user (send syscall returns sucess while I can't find that fragment in wireshark). It is very strange because the ServerHello is shallowed in network stack (in firewall, maybe?). After changing the network to cubic, the problem is gone immediately. For declaration, I am using the latest version of Windows 11 24H2 LTSC Iot Enterprise edition. And I have recorded the pcap file and will upload it if anyone needs to troubleshoot.
